variable_types_raw = c("1. Страна", "nominal",
          "2. Национальность", "nominal",
          "3. Срок проживания", "nominal", # rule in expected_corrs is like for  nominal data, hence adequate change is needed here
          "4. Место жительства", "nominal",
          "5. Планы на будущее", "nominal",
          "6. Знание языка", "ordinal",
          "7. Общение на работе", "ordinal",
          "8. Общение вне работы", "ordinal",
          "9. Дети должны", "ordinal",
          "10. Медиа на", "ordinal",
          "11.1. Взятки на границе", "binary",
          "11.2. Взятки в полиции", "binary",
          "11.3. Расовая дискриминация", "binary",
          "11.4. Религия", "binary",
          "11.5. Преступления", "binary",
          "11.6. Работа", "binary",
          "11.7. Низкая зп", "binary",
          "11.8. Работодатель мудак", "binary",
          "11.9. Тяжёлый труд", "binary",
          "11.10. Жильё", "binary",
          "11.11. Медицина", "binary",
          "11.12. Юри", "binary",
          "11.13. Русский", "binary",
          "11.14. Куда с проблемами", "binary",
          "11.15. Где работать  жить", "binary",
          "12. Есть диаспора?", "binary",
          "13. А вы в ней?", "binary",
          "14. Способ решения проблем", "nominal",
          "15. Гугл работы", "nominal",
          "16. Гугл жилья", "nominal",
          "17. НКО", "binary",
          "18. Создание семьи", "ordinal",
          "19. Получение гражданства", "ordinal",
          "20. Религиозность", "ordinal",
          "21. Возраст", "ordinal",
          "22. Образование", "ordinal"
)

variable_types_matrix = matrix(variable_types_raw, ncol=2, byrow = TRUE)